### PR TITLE
Add numeric ops

### PR DESCRIPTION
**Pull request by davidrpugh**
PR demonstrating how to add numeric operations for value classes like `Price` and `Quantity`.   This PR partially sorts issue #17.  A complete solution to that issue needs to wait until a couple of other PRs have been merged.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bherd-rb This PR is ready to go.  **Important that PR #20 gets merged first!**

**Comment by davidrpugh** [comment]
@bherd-rb Now that #20 has been merged, this PR is ready to go...

**Comment by rafabap** [comment]
Looks good to me! I guess you are allowing `Quantity` and `Price` to go negative?

**Comment by rafabap** [comment]
Sorry I see that just `Quantity` can be negative.

**Comment by davidrpugh** [comment]
@rafabap Actually even though I have set a `MinValue` for `Price` to be zero, there is no formal restriction forbidding the creation of negative prices.  

Should I place formal restrictions on the values?  Seems logical to restrict prices to be non-negative. The [Wellman et al (2001)](https://pdfs.semanticscholar.org/88eb/648f4c74c9e8ee50fd818a266b6f1b3b2ca3.pdf) paper allows quantities to be either positive or negative. Negative quantity would indicate an order to sell and positive quantity would indicate an order to buy. 

We are already differentiating between ask and bid orders using the type system so having quantities take different signs is a bit unnecessary.  What do you guys think?

There is another Scala-specific trade-off to consider.  Currently, both `Price` and `Quantity` extend `AnyVal` which means that the compiler will convert them to `Double` in the byte code and avoid the memory overhead associated with object creation.  As far as I know it is not possible to restrict the domain of the values and extend from `AnyVal`.  Restricting the values will force us to incur the memory overhead associated with storing all of the `Price` and `Quantity` instances.  I am not sure how much weight to place on this kind of micro optimization at this point.  If you feel the value restrictions would be useful, then I think we should impose them.

Thoughts?

**Pull request merged**
