### PR TITLE
Add tests!

### PR DESCRIPTION
**Pull request by davidrpugh**
This PR is for adding unit, functional, and performance tests to the code base.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bherd-rb I have found a bug in the `remove` method of the `FourHeapOrderBook` class.  Am working on a fix now.

**Comment by davidrpugh** [comment]
@bherd-rb I have fixed the bug and pushed these changes.  Let's merge this PR and I will open another one to add more tests...

**Review by bherd-rb — APPROVED** [review]

**Comment by davidrpugh** [comment]
@bherd-rb More tests...more bugs! But progress is being made...I am now working on sorting out and issue with discriminatory price double auctions.  Hopefully will have sorted soon...

**Comment by davidrpugh** [comment]
For now I am going to focus on unit and functional tests...and save performance testing for version 0.2.0 or later...

**Pull request merged**
