### PR TITLE
Now pricing rule must be passed to constructor.

### PR DESCRIPTION
**Pull request by davidrpugh**
This PR requires the user to pass a pricing rule as a constructor parameter when creating an auction.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bherd-rb I think I have come up with a solution that allows us to build different auctions by composing orderbooks, pricing rules, and eventually price quoting rules as desired.

The basic idea is to introduce a `WithOrderBook` class and a factory method called `withOrderBook` that allows the user to create an `WithOrderBook`  instance from a particular `orderBook` instance. `WithOrderBook` instances have `insert` and `remove` methods just like `Auctions` but have no `clear` method. `WithOrderBook` instance also have methods that take pricing rules as params and return auctions.

Let me know what you think.

**Comment by davidrpugh** [comment]
@bherd-rb If you have a chance, can you take a look at the proposed solution.  I think it is solid, but wouldn't mind discussing.  If we can merge this, then I have extended this solution to incorporate the quote policies in another branch.

**Review by bherd-rb — APPROVED** [review]

**Comment by bherd-rb** [comment]
@davidrpugh That looks like a great solution! Just to understand it correctly: if I wanted to change the pricing rule at runtime, I would simply call function `withUniformPricing` or `withDiscriminatoryPricing` on the existing auction object, pass the new pricing rule as an argument, and the order book would automatically be reused, is that correct?

**Comment by davidrpugh** [comment]
@bherd-rb  Exactly.  Here is the relevant piece from the worksheet...

```scala
// here we create a `WithOrderBook` object that encapsulates the order book (which is empty but need not be)...
val withOrderBook = DoubleAuction.withOrderBook(FourHeapOrderBook.empty[Google])
val withOrderBook2 = withOrderBook.insert(order3)
val withOrderBook3 = withOrderBook2.insert(order4)
val withOrderBook4 = withOrderBook3.insert(order9)
val withOrderBook5 = withOrderBook4.insert(order8)

// after inserting (or removing orders) now we can define the pricing rule...
val auction = withOrderBook5.withUniformPricing(midPointPricing)
val (result, _) = auction.clear
result.map(fills => fills.map(fill => fill.price).toList)

// ...because we still have the `withOrderBook5` object around we ca re-run the same auction with a different pricing rule!
val auction2 = withOrderBook5.withUniformPricing(askQuotePricing)
val (result2, _) = auction2.clear
result2.map(fills => fills.map(fill => fill.price).toList)

// ...or even like this...
val auction3 = withOrderBook5.withDiscriminatoryPricing(midPointPricing)
val (result3, _) = auction3.clear
result3.map(fills => fills.map(fill => fill.price).toList)
```
...I will update this branch and then merge.

**Pull request merged**
