### PR TITLE
Added a tick field to the Tradable trait.

### PR DESCRIPTION
**Pull request by davidrpugh**
@bherd-rb Here is the PR that adds a `tick` field to the `Tradable` trait as discussed in #34.  Can you take a look at your service implementation? I can not get Java to compile.  I tried many things and end the end just left boilerplate hoping that you can sort it.

Issue seems to be conversion between Scala Long and Java Long (Scala Long is a sub-type of Java Long); initial I thought that my use of a `Currency` type alias but this does not seem to be the case.

### CODE REVIEW

**Comment by bherd-rb** [comment]
@davidrpugh Sure, I'll take a look and see if I can fix it.

**Comment by bherd-rb** [comment]
@davidrpugh I've pushed a new version of the `Service` class seems to be working. As you can see, the solution isn't very elegant. The problem is that Java strictly requires a _method_ with return type `long` whereas the Scala trait -- as far as I can tell -- is agnostic of whether an implementation will contain a _method_ or just a _field_ which is clearly more flexible.

**Comment by davidrpugh** [comment]
@bherd-rb This is annoying.  Two possible solutions that I can think of...

1. I can not think of any reason why tick should be a method rather than a field and my use of `def` rather than `val` in the `Tradable` trait is out of habit and convention (as you correctly point out using `def` provides additional flexibility). Perhaps I can change the `def` to `val` and this will allow Java to understand that `tick` should be a field.
2. Other possibility would be to consider making `Tradable` and abstract class rather than a trait and passing `tick` as a constructor parameter.

I will implement both and you can tell me which one seems to work best...

**Comment by davidrpugh** [comment]
@bherd-rb There is now a `Tradable2` trait which uses a `val` instead of `def` and an `AbstractTradable` which uses an abstract class instead of a trait.  Let me know which of these implementations seems to be easier to use from the Java side...

**Comment by bherd-rb** [comment]
@davidrpugh Interestingly, that doesn't seem to make any difference. Both versions of `Tradable` seem to result in the same bytecode. If I disassemble `Tradable.class`, this is the result: 

```java
public interface org.economicsl.auctions.Tradable {
  public abstract long tick();
}
```

Exactly the same for `Tradable2`. So it seems we have to live with the cumbersome Java version for the time being. I'll keep searching for a better solution.

**Comment by bherd-rb** [comment]
@davidrpugh The abstract class version works much better. It gets compiled into the following (disassembled) bytecode: 

```java
public abstract class org.economicsl.auctions.AbstractTradable {
  public long tick();
  public org.economicsl.auctions.AbstractTradable(long);
}
```

As you can see, it contains both an abstract constructor and the implemented `tick()` function. This means that the instantiation can now be simplified as follows:

```java
public class Service extends AbstractTradable {
    public Service(long _tick) {
        super(_tick);
    }
} 
```
But what implications does that have on the Scala side? If you replace traits with abstract classes, can you still do mixin class composition?

**Comment by davidrpugh** [comment]
@bherd-rb on the Scala side it means that we can not mixin `Tradable` but rather would need extend from `Tradable` (we could still mixin other traits if we want/need to). 

What we lose is the ability to do things like...

```scala
class Thing(name: String)

class TradableThing(name, String, tick: Currency) extends Thing(name) with Tradable
```

...so basically we can not take an existing class and extend it to make it tradable by mixing in `Tradable`.

**Comment by bherd-rb** [comment]
@davidrpugh The current solution seems to work well in my case. I'm not 100% happy about the fact that we lose some flexibility w.r.t. mixing traits on the Scala side, but it seems to be the only solution if we want to support easy interoperability with Java. 

I think in this case the limitations are acceptable but if we are forced to give up even more Scala features in the future, then your suggestion to eventually re-write the code from scratch in Java once the API has stabilised is probably preferable.

**Review by bherd-rb — APPROVED** [review]

**Comment by davidrpugh** [comment]
@bherd-rb I am going to see if I can get away with the following solution...

```scala
trait Tradable {
 
   /** Minimum tick size. */
   def tick: Currency
 
 }

abstract class AbstractTradable(val tick: Currency) extends Tradable
```

I think this will allow mixin uses cases to use `Tradable` and those Java users to extend from `AbstractTradable` whilst to screwing up the type parameter bounds used throughout the API. If this works then I will merge and close this API later today.

**Comment by davidrpugh** [comment]
@bherd-rb can you push any changes to the Java API that are needed to this branch and then I will merge this PR.

**Comment by bherd-rb** [comment]
@davidrpugh Interestingly, `sbt package` works well. When I do `mvn package`, I get the following error: 

```
[ERROR] ./org/economicsl/auctions/singleunit/Electricity.scala:21: error: class Electricity needs to be abstract, since method tick in trait Tradable of type => org.economicsl.auctions.Currency is not defined
[ERROR] class Electricity extends Tradable
[ERROR]       ^
[ERROR] ./org/economicsl/auctions/singleunit/Painting.scala:23: error: class Guernica needs to be abstract, since method tick in trait Tradable of type => org.economicsl.auctions.Currency is not defined
[ERROR] class Guernica extends Painting
```

Do you have any idea what that could be?!

**Comment by bherd-rb** [comment]
@davidrpugh Ok, done. The only change I had to make was to add scalatest to the pom.file and to uncomment compilation of the test classes. The latter was necessary because `Electricity` and `Guernica'  haven't been adapted to the new Tradable (with the tick) yet. I didn't want to mess around with your code, so I just deactivated compilation. Hope that's OK.

**Comment by davidrpugh** [comment]
@bherd-rb Silly me! I have now fixed the issues with the test classes. Can you fix the `pom.xml` now?

**Pull request merged**
