### PR TITLE
Java versions of different auction types

### PR DESCRIPTION
**Pull request by bherd-rb**

### CODE REVIEW

**Review by davidrpugh — COMMENTED** [review]
@bherd-rb Do we need `JAppleStock`, `JParkingSpace` etc? I know that Java users can create instances of the Scala versions of these classes already.  I don't want to burden Java users with having to recreate various classes of `Tradable` as I expect that eventually we will have a full blown class hierarchy of such `Tradable` types.

What am I missing?

**Comment by bherd-rb** [comment]
@davidrpugh You're absolutely right, the Java versions of the tradables don't make any sense. I'll get rid of them.

**Review by davidrpugh — COMMENTED** [review]
@bherd-rb This looks good to me.  Clearly handling the streams is quite tedious on the Java side.  We should rethink the use of streams going forward.

Can you have the auction classes implement some kind of testing interface (JUnit?) so that the assert statements can be incorporated into the testing infrastructure?

**Comment by bherd-rb** [comment]
@davidrpugh Yes, absolutely. I'll add a testing infrastructure.

**Comment by bherd-rb** [comment]
@davidrpugh I have a question regarding the test cases. Essentially, all the stuff in `functional` are tests, right? At the current stage, the auction classes don't really contain any non-testing-related logic. As a consequence, shouldn't they go into `src/test`? 

I have committed a example of what a test class for the FPSBA could look like. Have a look and let me know what you think. Eventually, it could replace `JFirstPriceSealedBidAuction` in `functional`. Or am I misunderstanding the purpose of the stuff in `functional`?

**Comment by davidrpugh** [comment]
@bherd-rb Yes essentially everything in `src/functional` is testing logic.  I find it useful to distinguish between unit testing and functional (or end-to-end) testing. I have reserved `src/test` for unit tests which should be simple tests of individual method calls; `src/functions` tests should test properties of an entire "application."  For example, for some auctions one can derive closed form expressions for equilibrium bidding strategies.  Such closed form expressions can be used to generate orders which can then be fed in to the auction and we can test whether the auction returns the analytic result.

Admittedly the tests that we have in`src/functional` are not the best "end-to-end" tests that one could imagine.  Eventually we can port over some better examples from `agora`.

**Comment by davidrpugh** [comment]
@bherd-rb I have merged in the updates to the develop branch and fixed some basic import errors. Can you take a look at the remaining issues?

**Comment by davidrpugh** [comment]
@bherd-rb I see that there are some issues with the `Clearing` class.  This class is made obsolete in PR #61 so let's not worry too much about this error.

**Comment by davidrpugh** [comment]
@bherd-rb This branch has been effectively incorporated into develop by our recent work.

**Pull request closed without merging**
