### PR TITLE
First price auction

### PR DESCRIPTION
**Pull request by davidrpugh**
@bherd-rb This PR adds an example of a one-sided auction to the API.  Note that I have now created two new interfaces called `AuctionLike` and `ReverseAuctionLike` in order to separate the inserting and removing of ask orders from bid orders (i.e., we do not want users to be able to insert an ask order into a one-sided auction, we only want them to be able to insert/remove bid orders).

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bherd-rb Negligence on my part.  Good catch! The "diamond problem" is handled by the order in which traits are mixed in from right to left.  In this case, `DoubleAuction` would look for implementation of the clear method first in `ReverseAuctionLike` and then in `AuctionLike`.

**Comment by davidrpugh** [comment]
@bherd-rb Assuming that all of the status checks pass, this is ready for merge.  Note that this PR fixes a substantial bug in my implementation of the `FourHeapOrderBook`...that bug now has a unit test!

**Comment by davidrpugh** [comment]
@bherd-rb Let me know if you have questions about this PR, I would like to get it merged today if possible as it fixes a bug.

**Comment by davidrpugh** [comment]
@bherd-rb Are you happy to merge this PR? It is good to go on my end...

**Review by bherd-rb — APPROVED** [review]

**Pull request merged**
