### PR TITLE
Add four heap orderbook

### PR DESCRIPTION
**Pull request by davidrpugh**
PR that implements the four-heap order book algorithm described in Wellman et al 1998.  Current implementation works only for single unit orders.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@bherd there are a few outstanding issues with the implementation.  First the classes `MatchedOrders` and `UnMatchedOrders` are for internal use only and should not be part of the public API (i.e., need to be made `private`); second, currently there is nothing preventing orders for different tradable objects from getting added to the same order book.  Either the tradable object type needs to somehow be included in the order type (in which case this error could be caught by the compiler); or the return type of the `+` method for the order book needs to be something like `Try[FourHeapOrderBook]` in order to force the caller to explicitly deal with the failure.  Thoughts?

**Comment by davidrpugh** [comment]
@bherd Biggest outstanding issue with the implementation is that it does not work for `SinglePricePoint` orders (i.e., no multi-unit orders).

**Comment by bherd** [comment]
@davidrpugh Regarding the problem related with different types of tradable within the same order book: would it make sense to parametrise an order book with the type of tradable it accepts (by also parametrising the basic orders)? This would increase type safety. In general, it would be interesting to discuss how we are best going to mix dynamic and static polymorphism.

**Comment by davidrpugh** [comment]
@bherd I like the idea of maintaining type safety where ever possible.  I suppose one approach along the lines you suggested would look something like...

```scala
trait Order[+T <: Tradable] {
  
  def tradable: T

}

class OrderBook[+T <: Tradable, A <: AskOrder[T], B <: BidOrder[T]] {

  def +(order: A): OrderBook[T, A, B]

  def -(order: A): OrderBook[T, A, B] 
  ...
}
```
...I am not completely confident about that the variance annotations are correct above.

**Comment by bherd-rb** [comment]
Yes exactly, that's what I meant. I'm also not quite sure how Scala's variance annotations work, but in principle that looks fine. I need to go through the remaining pull requests and think whether the parametrised solution would cause any problems...

**Comment by davidrpugh** [comment]
@bherd-rb I was able to implement the solution discussed above.  Line 52 of the `sandbox.sc` worksheet is commented out.  If you un-comment this line, then the code will not compile because this line tries to add an order for `Apple` into and order book storing orders for `Google`.

Downside is that now the the signatures for creating instances of order books are quite verbose.  For example...

```scala
val orderBook = FourHeapOrderBook.empty[Google, LimitAskOrder[Google] with SingleUnit[Google], LimitBidOrder[Google] with SingleUnit[Google]]
```

...I think the ideal solution would be something like...

```scala
val orderBook = FourHeapOrderBook.empty[Google]
```

...which we might be able to get once the `FourHeapOrderBook` algorithm handle multi-unit orders.  Thoughts?

**Comment by bherd-rb** [comment]
@davidrpugh Great, I'll give it a try. But I agree that the type definition is not really user-friendly. C++ has some nice mechanisms to solve that problem. I'll check if Scala also offers something like that.

**Comment by davidrpugh** [comment]
@bherd-rb Will be interested to see what mechanisms C++ has for dealing with long type signatures.  Scala allows for type aliasing; perhaps there isn't any need for the `SingleUnit` mixin trait at all.  Could achieve exactly the same effect with an auxiliary constructor for `LimitAskOrder` and `LimitBidOrder` where `quantity = Quantity(1)` is set as the default.
 
Anyway, I have pushed a new PR #7 that achieves my ideal syntax just to facilitate discussion...

**Review by bherd-rb — APPROVED** [review]

**Pull request merged**
